[package]
name = "jinpyok_input"
version = "0.1.3"
edition = "2021"
author = ["Kim_Jin_Pyo"]
license = "MIT"
description = "My comfortable user input methods"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
